### ISSUE TITLE
Step 3 - app run/build error

### ISSUE THREAD

**Issue by RobMDoe** [Azure-Samples/azure-digital-twins-unreal-integration#5]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Problems with Step 3 'Simulate Devices'. Have used GIT in Windows CLI to clone 'mock-devices' and 'azure-digital-twins-unreal-integration' to my root folder C:\users\rober. Have copied hvac.ts, index.ts, smartbinary.ts files between as instructed. Changed path to src/client (incidentally, the copied code attaches client to npm), then > npm ci && npm run build. The app doesn't build.

### Any log messages given by the failure
>Attached below.

### Expected/desired behavior
>Run/build app

### OS and Version?
> Windows 11 Pro 

### Versions
> 21H2

### Mention any other details that might be useful
Otherwise all fine up to this stage of Step 3.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

[2022-02-04T23_36_02_363Z-debug - Copy.log](https://github.com/Azure-Samples/azure-digital-twins-unreal-integration/files/8009182/2022-02-04T23_36_02_363Z-debug.-.Copy.log)

**Comment by AshokPeddakotla-MSFT** [comment]
@stevebus Steve Busby FTE @SamWSP @3DStephen @marvin-garcia could you please help address this issue.
Related to : https://docs.microsoft.com/en-us/answers/questions/724488/index.html

**Comment by adamlash** [comment]
Hey @RobMDoe ,

It looks like the root of this issue is to do with a Dependency on the Simulator **note-sass** which uses the **node-gyp** package to compile various parts of the Simulator. It is expecting Python2.7 and VS 2017 C++ Tools to be installed and available somewhere on the path (or in the directories eg C:/Python27 or the VS default install dir)

As a workaround for now, the following should suffice:
- Install Python2.7 (https://www.python.org/download/releases/2.7/)
- Confirm VS 2017 Visual C++ Build tools is installed (This can be found at: https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15)

Re-run the command `npm ci && npm run build`


Let me know if this functions for you! I replicated this on a Virtual Machine and these were the steps required. I'll close off this issue in 2 weeks If I don't hear back.


Future fixes should remove the simulators dependency on *node-sass* as this has now been deprecated per: https://www.npmjs.com/package/node-sass. Will look into Simulators' build and consider if a PR is required to remove this deprecated dependency.

**Comment by RobMDoe** [comment]
Hi @adamlash . 
Thanks for your quick response. 
Python27 and VS 2017 Build Tools installed and now all running perfectly.

**Comment by stevebus** [comment]
@RobMDoe  - thanks for reporting the issue and let us know if you have any other problems!

@adamlash  - thanks for the research and the fix!
